# Generated by Django 3.0.5 on 2020-04-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_body',
            new_name='article_heading',
        ),
    ]
